version: '3.8'
services:
  db:
    image: mongo
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/dogWebDB
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  mongo_data:
