version: '3.8'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:27017/dogWebDB
      JWT_SECRET: Barkbark1234
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
       - /app/node_modules
    depends_on:
      - backend
volumes:
  mongo_data:
